import type { OutboxEntry, OutboxEntryInput } from '@/shared/electron-api.types';

/* eslint-disable @typescript-eslint/require-await -- no-op async IPC stubs for browser dev */
const noop = (): void => {};
const noopUnsub = (): (() => void) => () => {};
const noopAsync = async (): Promise<void> => {};

function stubOutboxEntry(entry: OutboxEntryInput, id: number): OutboxEntry {
  const now = Date.now();
  return {
    id,
    attemptCount: 0,
    createdAt: now,
    updatedAt: now,
    ...entry,
  };
}

/** No-op electronAPI for Vite browser dev when Electron preload is unavailable. */
export function createDevElectronApiStub(): typeof window.electronAPI {
  let nextOutboxId = 1;

  return {
    db: {
      saveMessage: noopAsync,
      getMessages: async () => [],
      listMeshtasticDmPeers: async () => [],
      saveNode: noopAsync,
      saveNodePath: noopAsync,
      getNodes: async () => [],
      clearMessages: noopAsync,
      clearNodes: noopAsync,
      deleteNode: noopAsync,
      updateMessageStatus: noopAsync,
      exportDb: async () => null,
      importDb: async () => null,
      deleteNodesByAge: noopAsync,
      deleteNodesNeverHeard: async () => 0,
      pruneNodesByCount: async () => ({ changes: 0 }),
      pruneMessagesByCount: async () => ({ changes: 0 }),
      pruneMeshcoreMessagesByCount: async () => ({ changes: 0 }),
      pruneReticulumMessagesByCount: async () => ({ changes: 0 }),
      listRrcMessages: async () => [],
      insertRrcMessage: async () => ({ changes: 0 }),
      listRrcNicks: async () => [],
      upsertRrcNick: async () => ({ changes: 0 }),
      deleteRrcMessagesByRoom: async () => ({ changes: 0 }),
      pruneRrcMessagesByCount: async () => ({ changes: 0 }),
      pruneRrcMessagesByAge: async () => ({ changes: 0 }),
      pruneReticulumDestinationsByCount: async () => ({ changes: 0 }),
      deleteReticulumDestinationsByAge: async () => ({ changes: 0 }),
      pruneReticulumIdentityActivityByAge: async () => ({ changes: 0 }),
      deleteNodesBatch: async () => 0,
      clearMessagesByChannel: noopAsync,
      getMessageChannels: async () => [],
      getBlockedContacts: async () => [],
      blockContact: async () => ({ changes: 1 }),
      unblockContact: async () => ({ changes: 1 }),
      listReticulumRemoteAddresses: async () => [],
      listReticulumInboundPolicy: async () => [],
      setNodeFavorited: noopAsync,
      getNodeNote: async () => null,
      setNodeNote: noopAsync,
      deleteNodesBySource: async () => 0,
      migrateRfStubNodes: async () => 0,
      deleteNodesWithoutLongname: async () => 0,
      prunePositionHistory: async () => 0,
      prunePositionHistoryPerNode: async () => 0,
      clearNodePositions: noopAsync,
      updateMessageReceivedVia: noopAsync,
      updateMessagePacketId: noopAsync,
      getMeshcoreMessages: async () => [],
      listMeshcoreDmPeers: async () => [],
      getReticulumMessages: async () => [],
      clearReticulumMessages: async () => ({ changes: 0 }),
      clearReticulumContactDestinations: async () => ({ changes: 0 }),
      saveReticulumMessage: noopAsync,
      markStaleReticulumOutbound: async () => ({ changes: 0 }),
      vacuumReticulumTables: async () => ({ ok: true }),
      getReticulumDestinations: async () => [],
      getReticulumIdentityActivity: async () => [],
      getReticulumIdentityActivityByIdentity: async () => [],
      deleteReticulumDestination: async () => ({ changes: 1 }),
      upsertReticulumDestination: noopAsync,
      upsertReticulumIdentityActivity: async () => ({ changes: 1 }),
      upsertReticulumIdentityActivityBatch: async () => ({ changes: 0 }),
      searchMessages: async () => [],
      searchMeshcoreMessages: async () => [],
      getMeshcoreContacts: async () => [],
      saveMeshcoreMessage: noopAsync,
      updateMeshcoreMessageSender: noopAsync,
      saveMeshcoreContact: noopAsync,
      saveMeshcoreContactsBatch: async () => 0,
      updateMeshcoreContactRfTransport: noopAsync,
      updateMeshcoreContactAdvert: noopAsync,
      updateMeshcoreContactType: noopAsync,
      updateMeshcoreContactLastRf: noopAsync,
      updateMeshcoreMessageStatus: noopAsync,
      updateMeshcoreMessageStatusByKey: async () => ({ changes: 1 }),
      deleteMeshcoreContact: noopAsync,
      clearMeshcoreMessages: noopAsync,
      getMeshcoreMessageChannels: async () => [],
      clearMeshcoreMessagesByChannel: noopAsync,
      clearMeshcoreContacts: noopAsync,
      deleteMeshcoreContactsNeverAdvertised: noopAsync,
      deleteMeshcoreContactsByAge: noopAsync,
      pruneMeshcoreContactsByCount: async () => ({ changes: 0 }),
      clearMeshcoreRepeaters: noopAsync,
      markAllMeshcoreContactsOffRadio: noopAsync,
      getMeshcoreContactCount: async () => 0,
      deleteMeshcoreContactsWithoutPubkey: async () => ({ deleted: 0, excludedStubCount: 0 }),
      offloadAllMeshcoreContacts: async () => 0,
      markMeshcoreContactOffRadio: async () => ({ changes: 0 }),
      getMeshcoreContactById: async () => null,
      updateMeshcoreContactNickname: noopAsync,
      updateMeshcoreContactFavorited: noopAsync,
      savePositionHistory: noopAsync,
      getPositionHistory: async () => [],
      clearPositionHistory: noopAsync,
      saveMeshcoreHopHistory: async () => true,
      getMeshcoreHopHistory: async () => null,
      getAllMeshcoreHopHistory: async () => [],
      saveMeshcoreTraceHistory: async () => true,
      getMeshcoreTraceHistory: async () => [],
      pruneMeshcorePathHistory: async () => true,
      upsertMeshcorePathHistory: async () => true,
      recordMeshcorePathOutcome: async () => true,
      getMeshcorePathHistory: async () => [],
      getAllMeshcorePathHistory: async () => [],
      deleteMeshcorePathHistoryForNode: async () => true,
      deleteAllMeshcorePathHistory: async () => true,
      getContactGroups: async () => [],
      createContactGroup: async () => 1,
      updateContactGroup: noopAsync,
      deleteContactGroup: noopAsync,
      addContactToGroup: noopAsync,
      removeContactFromGroup: noopAsync,
      getContactGroupMembers: async () => [],
    },
    mqtt: {
      connect: noopAsync,
      disconnect: noopAsync,
      powerResume: noopAsync,
      powerSuspend: noopAsync,
      onStatus: noopUnsub,
      onError: noopUnsub,
      onWarning: noopUnsub,
      onNodeUpdate: noopUnsub,
      onMessage: noopUnsub,
      onBrokerRaw: noopUnsub,
      onTraceRouteReply: noopUnsub,
      onClientId: noopUnsub,
      getClientId: async () => '',
      getCachedNodes: async () => [],
      getChannelNameToIndex: async () => ({}),
      updateChannelKeys: noopAsync,
      updateTopicPrefix: noopAsync,
      publish: async () => 1,
      publishProxy: noopAsync,
      publishNodeInfo: async () => 1,
      publishPosition: async () => 1,
      publishWaypoint: async () => 1,
      publishMeshcore: noopAsync,
      publishMeshcorePacketLog: noopAsync,
      onMeshcoreChat: noopUnsub,
      refreshMeshcoreToken: async () => null,
      updateMeshcoreToken: noopAsync,
      onRequestTokenRefresh: noopUnsub,
    },
    onNobleBleAdapterState: noopUnsub,
    onNobleBleDeviceDiscovered: noopUnsub,
    onNobleBleLinkRssi: noopUnsub,
    onNobleBleConnected: noopUnsub,
    onNobleBleDisconnected: noopUnsub,
    onNobleBleConnectAborted: noopUnsub,
    onNobleBleFromRadio: noopUnsub,
    startNobleBleScanning: async () => ({ ok: true as const }),
    stopNobleBleScanning: noopAsync,
    connectNobleBle: async () => ({ ok: true }),
    disconnectNobleBle: noopAsync,
    isNobleBleConnected: async () => false,
    nobleBleToRadio: noopAsync,
    onSerialPortsDiscovered: noopUnsub,
    selectSerialPort: noop,
    cancelSerialSelection: noop,
    onBluetoothDevicesDiscovered: noopUnsub,
    selectBluetoothDevice: noop,
    cancelBluetoothSelection: async () => ({ cancelled: false }),
    bluetoothUnpair: noopAsync,
    bluetoothStartScan: noopAsync,
    bluetoothStopScan: noopAsync,
    bluetoothPair: noopAsync,
    bluetoothConnect: noopAsync,
    bluetoothUntrust: noopAsync,
    bluetoothGetInfo: async () => '',
    onBluetoothPinRequired: noopUnsub,
    provideBluetoothPin: noop,
    cancelBluetoothPairing: noop,
    resetBlePairingRetryCount: noop,
    clearSessionData: noopAsync,
    getGpsFix: async () => ({ lat: 0, lon: 0, source: 'ip' as const }),
    update: {
      check: noopAsync,
      download: noopAsync,
      install: noopAsync,
      openReleases: noopAsync,
      onAvailable: noopUnsub,
      onNotAvailable: noopUnsub,
      onChecking: noopUnsub,
      onProgress: noopUnsub,
      onDownloaded: noopUnsub,
      onError: noopUnsub,
    },
    notifyDeviceConnected: noop,
    notifyDeviceDisconnected: noop,
    setTrayUnread: noop,
    quitApp: noopAsync,
    restartApp: noopAsync,
    getPlatform: () => 'linux',
    showEmojiPanel: noopAsync,
    clipboard: {
      writeText: noopAsync,
    },
    notify: {
      show: noopAsync,
      longSessionRestart: noopAsync,
      clearLongSessionNudge: noopAsync,
    },
    safeStorage: {
      encrypt: async () => null,
      decrypt: async () => null,
      isAvailable: async () => false,
    },
    appSettings: {
      getLoginItem: async () => ({ openAtLogin: false }),
      setLoginItem: noopAsync,
      getAll: async () => ({}),
      set: async () => ({ changes: 1 }),
    },
    onPowerSuspend: noopUnsub,
    onPowerResume: noopUnsub,
    sendRendererHeartbeat: async () => {},
    getProcessUptimeSec: async () => 0,
    app: {
      getRendererLiveness: async () => ({
        mainUptimeSec: 0,
        lastRendererHeartbeatAgeMs: null,
        rendererUnresponsiveSeen: false,
        rss: 0,
        heapUsed: 0,
      }),
    },
    onSpellcheckReplace: noopUnsub,
    meshcore: {
      tcp: {
        connect: noopAsync,
        write: noopAsync,
        disconnect: noopAsync,
        onData: noopUnsub,
        onDisconnected: noopUnsub,
      },
      openJsonFile: async () => null,
    },
    http: {
      preflight: noopAsync,
      connect: noopAsync,
      write: noopAsync,
      disconnect: noopAsync,
      onData: noopUnsub,
    },
    hostLink: {
      probeHttpRtt: async () => null,
      probeTcpRtt: async () => null,
      getSessionMeter: async () => null,
    },
    meshtastic: {
      tcp: {
        connect: noopAsync,
        write: noopAsync,
        disconnect: noopAsync,
        onData: noopUnsub,
        onDisconnected: noopUnsub,
      },
    },
    chat: {
      export: async () => ({ success: false }),
      saveReticulumAttachment: async () => ({ success: false }),
      showItemInFolder: async () => ({ ok: true }),
      readReticulumAttachmentAsDataUrl: async () => ({ dataUrl: null }),
      linkPreview: {
        fetch: async () => null,
      },
      outbox: {
        list: async () => [],
        add: async (entry: OutboxEntryInput) => stubOutboxEntry(entry, nextOutboxId++),
        updateStatus: noopAsync,
        remove: noopAsync,
      },
    },
    meshtasticXmodem: {
      pickUploadFile: async () => null,
      saveDownloadFile: async () => ({ success: false }),
    },
    support: {
      exportBundle: async () => null,
    },
    log: {
      getPath: async () => '/tmp/dev-browser.log',
      getRecentLines: async () => [],
      clear: noopAsync,
      export: async () => null,
      onLine: noopUnsub,
      logDeviceConnection: noopAsync,
    },
    tak: {
      start: noopAsync,
      stop: noopAsync,
      getStatus: async () => ({ running: false, port: 8089, clientCount: 0 }),
      getConnectedClients: async () => [],
      generateDataPackage: noopAsync,
      regenerateCertificates: noopAsync,
      pushNodeUpdate: noopAsync,
      onStatus: noopUnsub,
      onClientConnected: noopUnsub,
      onClientDisconnected: noopUnsub,
    },
    bleCoexistence: {
      register: async () => ({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      unregister: async () => ({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      assertCanConnect: async () => ({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      getState: async () => ({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      acquireScan: async () => ({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      releaseScan: async () => ({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      pauseNobleScan: async () => ({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      suspendNobleForReticulumBleConnect: async () => ({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
    },
    reticulum: {
      start: async () => ({ running: false, port: 0, pid: null }),
      stop: noopAsync,
      getStatus: async () => ({ running: false, port: 0, pid: null }),
      syncInterfaceIssueScope: async () => ({ running: false, port: 0, pid: null }),
      proxyGet: async () => ({}),
      proxyPost: async () => ({ ok: true }),
      proxyPut: async () => ({ ok: true }),
      proxyDelete: async () => ({ ok: true }),
      readDefaultConfigFile: async () => ({ path: null, content: null }),
      showConfigImportDialog: async () => ({ path: null, content: null }),
      onEvent: noopUnsub,
      onVoiceAudio: noopUnsub,
      onStatus: noopUnsub,
      rncp: {
        send: async () => ({ ok: false, error: 'stub' }),
        fetch: async () => ({ ok: false, error: 'stub' }),
        cancel: async () => ({ ok: true }),
        accept: async () => ({ ok: false, error: 'stub' }),
        reject: async () => ({ ok: true }),
        getStatus: async () => ({ transfers: [], pending_offers: [] }),
        getListener: async () => ({
          enabled: false,
          inbound_mode: 'off',
          allowed: [],
          blocked: [],
        }),
        setListener: async () => ({ ok: false, error: 'stub' }),
        announce: async () => ({ ok: false, error: 'stub' }),
        showOpenFileDialog: async () => ({ canceled: true, path: null }),
        showSaveDirectoryDialog: async () => ({ canceled: true, path: null }),
        revealInFolder: async () => ({ ok: false, error: 'stub' }),
      } satisfies typeof window.electronAPI.reticulum.rncp,
      rrc: {
        listHubs: async () => ({ hubs: [] }),
        upsertHub: async () => ({ ok: true }),
        setFavorite: async () => ({ ok: true }),
        connect: async () => ({ ok: false, error: 'stub' }),
        disconnect: async () => ({ ok: true }),
        getStatus: async () => ({
          sessions: [],
          identity_hash: null,
        }),
        join: async () => ({ ok: false, error: 'stub' }),
        part: async () => ({ ok: false, error: 'stub' }),
        send: async () => ({ ok: false, error: 'stub' }),
        setNickname: async () => ({ ok: false, error: 'stub' }),
        getRooms: async () => ({ rooms: [] }),
      },
    },
    vault: {
      setPasscode: async () => ({ ok: true }),
      unlock: async () => ({ ok: true }),
      lock: async () => ({ ok: true }),
      status: async () => ({ configured: false, unlocked: false }),
    },
  } as unknown as typeof window.electronAPI;
}

/** Install a no-op bridge when opening the Vite dev server in a plain browser tab. */
export function installDevElectronApiStubIfNeeded(): boolean {
  if (typeof window.electronAPI !== 'undefined') return false;
  if (!import.meta.env.DEV) return false;
  window.electronAPI = createDevElectronApiStub();
  console.debug(
    '[dev] Installed browser electronAPI stub — use the Electron window for RF, SQLite, and IPC',
  );
  return true;
}
