import { vi } from 'vitest';

import type { ElectronAPI, OutboxEntry, OutboxEntryInput } from '@/shared/electron-api.types';

const outboxMockRows: OutboxEntry[] = [];
let outboxMockIdSeq = 1;

/** Reset in-memory outbox rows between renderer-ui tests. */
export function resetElectronAPIOutboxMock(): void {
  outboxMockRows.length = 0;
  outboxMockIdSeq = 1;
}

function makeOutboxMockRow(entry: OutboxEntryInput): OutboxEntry {
  const now = Date.now();
  return {
    id: outboxMockIdSeq++,
    attemptCount: 0,
    createdAt: now,
    updatedAt: now,
    ...entry,
  };
}

/** Full typed electronAPI stub for renderer-ui tests (extracted from setup for reuse). */
export function createElectronAPIMock(): ElectronAPI {
  return {
    db: {
      saveMessage: vi.fn().mockResolvedValue(undefined),
      getMessages: vi.fn().mockResolvedValue([]),
      listMeshtasticDmPeers: vi.fn().mockResolvedValue([]),
      saveNode: vi.fn().mockResolvedValue(undefined),
      saveNodePath: vi.fn().mockResolvedValue(undefined),
      getNodes: vi.fn().mockResolvedValue([]),
      clearMessages: vi.fn().mockResolvedValue(undefined),
      clearNodes: vi.fn().mockResolvedValue(undefined),
      deleteNode: vi.fn().mockResolvedValue(undefined),
      updateMessageStatus: vi.fn().mockResolvedValue(undefined),
      exportDb: vi.fn().mockResolvedValue(undefined),
      importDb: vi.fn().mockResolvedValue(undefined),
      deleteNodesByAge: vi.fn().mockResolvedValue(0),
      deleteNodesNeverHeard: vi.fn().mockResolvedValue(0),
      pruneNodesByCount: vi.fn().mockResolvedValue({ changes: 0 }),
      pruneMessagesByCount: vi.fn().mockResolvedValue({ changes: 0 }),
      pruneMeshcoreMessagesByCount: vi.fn().mockResolvedValue({ changes: 0 }),
      pruneReticulumMessagesByCount: vi.fn().mockResolvedValue({ changes: 0 }),
      listRrcMessages: vi.fn().mockResolvedValue([]),
      insertRrcMessage: vi.fn().mockResolvedValue({ changes: 1 }),
      listRrcNicks: vi.fn().mockResolvedValue([]),
      upsertRrcNick: vi.fn().mockResolvedValue({ changes: 1 }),
      deleteRrcMessagesByRoom: vi.fn().mockResolvedValue({ changes: 0 }),
      pruneRrcMessagesByCount: vi.fn().mockResolvedValue({ changes: 0 }),
      pruneRrcMessagesByAge: vi.fn().mockResolvedValue({ changes: 0 }),
      pruneReticulumDestinationsByCount: vi.fn().mockResolvedValue({ changes: 0 }),
      deleteReticulumDestinationsByAge: vi.fn().mockResolvedValue({ changes: 0 }),
      pruneReticulumIdentityActivityByAge: vi.fn().mockResolvedValue({ changes: 0 }),
      deleteNodesBatch: vi.fn().mockResolvedValue(0),
      clearMessagesByChannel: vi.fn().mockResolvedValue(undefined),
      getMessageChannels: vi.fn().mockResolvedValue([]),
      setNodeFavorited: vi.fn().mockResolvedValue(undefined),
      getNodeNote: vi.fn().mockResolvedValue(null),
      setNodeNote: vi.fn().mockResolvedValue(undefined),
      deleteNodesBySource: vi.fn().mockResolvedValue(0),
      migrateRfStubNodes: vi.fn().mockResolvedValue(0),
      deleteNodesWithoutLongname: vi.fn().mockResolvedValue(0),
      prunePositionHistory: vi.fn().mockResolvedValue(0),
      prunePositionHistoryPerNode: vi.fn().mockResolvedValue(0),
      clearNodePositions: vi.fn().mockResolvedValue(undefined),
      updateMessageReceivedVia: vi.fn().mockResolvedValue(undefined),
      updateMessagePacketId: vi.fn().mockResolvedValue(undefined),
      getMeshcoreMessages: vi.fn().mockResolvedValue([]),
      listMeshcoreDmPeers: vi.fn().mockResolvedValue([]),
      getReticulumMessages: vi.fn().mockResolvedValue([]),
      searchReticulumMessages: vi.fn().mockResolvedValue([]),
      deleteReticulumMessage: vi.fn().mockResolvedValue({ changes: 1 }),
      clearReticulumMessages: vi.fn().mockResolvedValue({ changes: 0 }),
      clearReticulumContactDestinations: vi.fn().mockResolvedValue({ changes: 0 }),
      saveReticulumMessage: vi.fn().mockResolvedValue(undefined),
      markStaleReticulumOutbound: vi.fn().mockResolvedValue({ changes: 0 }),
      vacuumReticulumTables: vi.fn().mockResolvedValue({ ok: true }),
      getReticulumDestinations: vi.fn().mockResolvedValue([]),
      setReticulumDestinationVerified: vi.fn().mockResolvedValue({ changes: 1 }),
      deleteReticulumDestination: vi.fn().mockResolvedValue({ changes: 1 }),
      upsertReticulumDestination: vi.fn().mockResolvedValue(undefined),
      getBlockedContacts: vi.fn().mockResolvedValue([]),
      blockContact: vi.fn().mockResolvedValue({ changes: 1 }),
      unblockContact: vi.fn().mockResolvedValue({ changes: 1 }),
      exportBlockedContacts: vi.fn().mockResolvedValue([]),
      importBlockedContacts: vi.fn().mockResolvedValue({ imported: 0, skipped: 0 }),
      getReticulumIdentityActivity: vi.fn().mockResolvedValue([]),
      getReticulumIdentityActivityByIdentity: vi.fn().mockResolvedValue([]),
      upsertReticulumIdentityActivity: vi.fn().mockResolvedValue({ changes: 1 }),
      upsertReticulumIdentityActivityBatch: vi.fn().mockResolvedValue({ changes: 1 }),
      listReticulumRemoteAddresses: vi.fn().mockResolvedValue([]),
      upsertReticulumRemoteAddress: vi.fn().mockResolvedValue({ changes: 1 }),
      deleteReticulumRemoteAddress: vi.fn().mockResolvedValue({ changes: 1 }),
      listReticulumInboundPolicy: vi.fn().mockResolvedValue([]),
      upsertReticulumInboundPolicy: vi.fn().mockResolvedValue({ changes: 1 }),
      deleteReticulumInboundPolicy: vi.fn().mockResolvedValue({ changes: 1 }),
      searchMessages: vi.fn().mockResolvedValue([]),
      searchMeshcoreMessages: vi.fn().mockResolvedValue([]),
      getMeshcoreContacts: vi.fn().mockResolvedValue([]),
      saveMeshcoreMessage: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreMessageSender: vi.fn().mockResolvedValue(undefined),
      saveMeshcoreContact: vi.fn().mockResolvedValue(undefined),
      saveMeshcoreContactsBatch: vi.fn().mockResolvedValue(0),
      updateMeshcoreContactRfTransport: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreContactAdvert: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreContactType: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreContactLastRf: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreMessageStatus: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreMessageStatusByKey: vi.fn().mockResolvedValue({ changes: 1 }),
      deleteMeshcoreContact: vi.fn().mockResolvedValue(undefined),
      clearMeshcoreMessages: vi.fn().mockResolvedValue(undefined),
      getMeshcoreMessageChannels: vi.fn().mockResolvedValue([]),
      clearMeshcoreMessagesByChannel: vi.fn().mockResolvedValue(undefined),
      clearMeshcoreContacts: vi.fn().mockResolvedValue(undefined),
      deleteMeshcoreContactsNeverAdvertised: vi.fn().mockResolvedValue(0),
      deleteMeshcoreContactsByAge: vi.fn().mockResolvedValue(0),
      pruneMeshcoreContactsByCount: vi.fn().mockResolvedValue({ changes: 0 }),
      clearMeshcoreRepeaters: vi.fn().mockResolvedValue(undefined),
      markAllMeshcoreContactsOffRadio: vi.fn().mockResolvedValue(undefined),
      getMeshcoreContactCount: vi.fn().mockResolvedValue(0),
      deleteMeshcoreContactsWithoutPubkey: vi
        .fn()
        .mockResolvedValue({ deleted: 0, excludedStubCount: 0 }),
      offloadAllMeshcoreContacts: vi.fn().mockResolvedValue(0),
      markMeshcoreContactOffRadio: vi.fn().mockResolvedValue({ changes: 0 }),
      getMeshcoreContactById: vi.fn().mockResolvedValue(null),
      updateMeshcoreContactNickname: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreContactFavorited: vi.fn().mockResolvedValue(undefined),
      savePositionHistory: vi.fn().mockResolvedValue(undefined),
      getPositionHistory: vi.fn().mockResolvedValue([]),
      clearPositionHistory: vi.fn().mockResolvedValue(undefined),
      saveMeshcoreHopHistory: vi.fn().mockResolvedValue(true),
      getMeshcoreHopHistory: vi.fn().mockResolvedValue(null),
      getAllMeshcoreHopHistory: vi.fn().mockResolvedValue([]),
      saveMeshcoreTraceHistory: vi.fn().mockResolvedValue(true),
      getMeshcoreTraceHistory: vi.fn().mockResolvedValue([]),
      pruneMeshcorePathHistory: vi.fn().mockResolvedValue(true),
      upsertMeshcorePathHistory: vi.fn().mockResolvedValue(true),
      recordMeshcorePathOutcome: vi.fn().mockResolvedValue(true),
      getMeshcorePathHistory: vi.fn().mockResolvedValue([]),
      getAllMeshcorePathHistory: vi.fn().mockResolvedValue([]),
      deleteMeshcorePathHistoryForNode: vi.fn().mockResolvedValue(true),
      deleteAllMeshcorePathHistory: vi.fn().mockResolvedValue(true),
      getContactGroups: vi.fn().mockResolvedValue([]),
      createContactGroup: vi.fn().mockResolvedValue(1),
      updateContactGroup: vi.fn().mockResolvedValue(undefined),
      deleteContactGroup: vi.fn().mockResolvedValue(undefined),
      addContactToGroup: vi.fn().mockResolvedValue(undefined),
      removeContactFromGroup: vi.fn().mockResolvedValue(undefined),
      getContactGroupMembers: vi.fn().mockResolvedValue([]),
    },
    mqtt: {
      connect: vi.fn().mockResolvedValue(undefined),
      disconnect: vi.fn().mockResolvedValue(undefined),
      powerResume: vi.fn().mockResolvedValue(undefined),
      powerSuspend: vi.fn().mockResolvedValue(undefined),
      onStatus: vi.fn().mockReturnValue(() => {}),
      onError: vi.fn().mockReturnValue(() => {}),
      onWarning: vi.fn().mockReturnValue(() => {}),
      onNodeUpdate: vi.fn().mockReturnValue(() => {}),
      onMessage: vi.fn().mockReturnValue(() => {}),
      onBrokerRaw: vi.fn().mockReturnValue(() => {}),
      onTraceRouteReply: vi.fn().mockReturnValue(() => {}),
      onClientId: vi.fn().mockReturnValue(() => {}),
      getClientId: vi.fn().mockResolvedValue(''),
      getCachedNodes: vi.fn().mockResolvedValue([]),
      getChannelNameToIndex: vi.fn().mockResolvedValue({}),
      updateChannelKeys: vi.fn().mockResolvedValue(undefined),
      updateTopicPrefix: vi.fn().mockResolvedValue(undefined),
      publish: vi.fn().mockResolvedValue(1),
      publishProxy: vi.fn().mockResolvedValue(undefined),
      publishNodeInfo: vi.fn().mockResolvedValue(1),
      publishPosition: vi.fn().mockResolvedValue(1),
      publishWaypoint: vi.fn().mockResolvedValue(1),
      publishMeshcore: vi.fn().mockResolvedValue(undefined),
      publishMeshcorePacketLog: vi.fn().mockResolvedValue(undefined),
      onMeshcoreChat: vi.fn().mockReturnValue(() => {}),
      refreshMeshcoreToken: vi.fn().mockResolvedValue(null),
      updateMeshcoreToken: vi.fn().mockResolvedValue(undefined),
      onRequestTokenRefresh: vi.fn().mockReturnValue(() => {}),
    },
    onNobleBleAdapterState: vi.fn().mockReturnValue(() => {}),
    onNobleBleDeviceDiscovered: vi.fn().mockReturnValue(() => {}),
    onNobleBleLinkRssi: vi.fn().mockReturnValue(() => {}),
    onNobleBleConnected: vi.fn().mockReturnValue(() => {}),
    onNobleBleDisconnected: vi.fn().mockReturnValue(() => {}),
    onNobleBleConnectAborted: vi.fn().mockReturnValue(() => {}),
    onNobleBleFromRadio: vi.fn().mockReturnValue(() => {}),
    startNobleBleScanning: vi.fn().mockResolvedValue({ ok: true }),
    stopNobleBleScanning: vi.fn().mockResolvedValue(undefined),
    connectNobleBle: vi.fn().mockResolvedValue({ ok: true }),
    disconnectNobleBle: vi.fn().mockResolvedValue(undefined),
    isNobleBleConnected: vi.fn().mockResolvedValue(true),
    nobleBleToRadio: vi.fn().mockResolvedValue(undefined),
    onSerialPortsDiscovered: vi.fn().mockReturnValue(() => {}),
    selectSerialPort: vi.fn(),
    cancelSerialSelection: vi.fn(),
    onBluetoothDevicesDiscovered: vi.fn().mockReturnValue(() => {}),
    selectBluetoothDevice: vi.fn(),
    cancelBluetoothSelection: vi.fn().mockResolvedValue({ cancelled: false }),
    bluetoothUnpair: vi.fn().mockResolvedValue(undefined),
    bluetoothStartScan: vi.fn().mockResolvedValue(undefined),
    bluetoothStopScan: vi.fn().mockResolvedValue(undefined),
    bluetoothPair: vi.fn().mockResolvedValue(undefined),
    bluetoothConnect: vi.fn().mockResolvedValue(undefined),
    bluetoothUntrust: vi.fn().mockResolvedValue(undefined),
    bluetoothGetInfo: vi.fn().mockResolvedValue(''),
    onBluetoothPinRequired: vi.fn().mockReturnValue(() => {}),
    provideBluetoothPin: vi.fn(),
    cancelBluetoothPairing: vi.fn(),
    resetBlePairingRetryCount: vi.fn(),
    clearSessionData: vi.fn().mockResolvedValue(undefined),
    getGpsFix: vi.fn().mockResolvedValue({ lat: 0, lon: 0, source: 'ip' }),
    update: {
      check: vi.fn().mockResolvedValue(undefined),
      download: vi.fn().mockResolvedValue(undefined),
      install: vi.fn().mockResolvedValue(undefined),
      openReleases: vi.fn().mockResolvedValue(undefined),
      onAvailable: vi.fn().mockReturnValue(() => {}),
      onNotAvailable: vi.fn().mockReturnValue(() => {}),
      onChecking: vi.fn().mockReturnValue(() => {}),
      onProgress: vi.fn().mockReturnValue(() => {}),
      onDownloaded: vi.fn().mockReturnValue(() => {}),
      onError: vi.fn().mockReturnValue(() => {}),
    },
    notifyDeviceConnected: vi.fn(),
    notifyDeviceDisconnected: vi.fn(),
    setTrayUnread: vi.fn(),
    quitApp: vi.fn().mockResolvedValue(undefined),
    restartApp: vi.fn().mockResolvedValue(undefined),
    notify: {
      show: vi.fn().mockResolvedValue(undefined),
      longSessionRestart: vi.fn().mockResolvedValue(undefined),
      clearLongSessionNudge: vi.fn().mockResolvedValue(undefined),
    },
    getPlatform: vi.fn().mockReturnValue('linux'),
    showEmojiPanel: vi.fn().mockResolvedValue(undefined),
    media: {
      ensureMicrophoneAccess: vi.fn().mockResolvedValue({ granted: true, status: 'granted' }),
      ensureCameraAccess: vi.fn().mockResolvedValue({ granted: true, status: 'granted' }),
    },
    clipboard: {
      writeText: vi.fn().mockResolvedValue(undefined),
    },
    safeStorage: {
      encrypt: vi.fn().mockResolvedValue(null),
      decrypt: vi.fn().mockResolvedValue(null),
      isAvailable: vi.fn().mockResolvedValue(false),
    },
    appSettings: {
      getLoginItem: vi.fn().mockResolvedValue({ openAtLogin: false }),
      setLoginItem: vi.fn().mockResolvedValue(undefined),
      getAll: vi.fn().mockResolvedValue({}),
      set: vi.fn().mockResolvedValue({ changes: 1 }),
    },
    onPowerSuspend: vi.fn().mockReturnValue(() => {}),
    onPowerResume: vi.fn().mockReturnValue(() => {}),
    sendRendererHeartbeat: vi.fn().mockResolvedValue(undefined),
    getProcessUptimeSec: vi.fn().mockResolvedValue(0),
    app: {
      getRendererLiveness: vi.fn().mockResolvedValue({
        mainUptimeSec: 0,
        lastRendererHeartbeatAgeMs: null,
        rendererUnresponsiveSeen: false,
        rss: 0,
        heapUsed: 0,
      }),
    },
    onSpellcheckReplace: vi.fn().mockReturnValue(() => {}),
    meshcore: {
      tcp: {
        connect: vi.fn().mockResolvedValue(undefined),
        write: vi.fn().mockResolvedValue(undefined),
        disconnect: vi.fn().mockResolvedValue(undefined),
        onData: vi.fn().mockReturnValue(() => {}),
        onDisconnected: vi.fn().mockReturnValue(() => {}),
      },
      openJsonFile: vi.fn().mockResolvedValue(null),
    },
    http: {
      preflight: vi.fn().mockResolvedValue(undefined),
      connect: vi.fn().mockResolvedValue(undefined),
      write: vi.fn().mockResolvedValue(undefined),
      disconnect: vi.fn().mockResolvedValue(undefined),
      onData: vi.fn().mockReturnValue(() => {}),
    },
    hostLink: {
      probeHttpRtt: vi.fn().mockResolvedValue(null),
      probeTcpRtt: vi.fn().mockResolvedValue(null),
      getSessionMeter: vi.fn().mockResolvedValue(null),
    },
    meshtastic: {
      tcp: {
        connect: vi.fn().mockResolvedValue(undefined),
        write: vi.fn().mockResolvedValue(undefined),
        disconnect: vi.fn().mockResolvedValue(undefined),
        onData: vi.fn().mockReturnValue(() => {}),
        onDisconnected: vi.fn().mockReturnValue(() => {}),
      },
    },
    chat: {
      export: vi.fn().mockResolvedValue({ success: false }),
      saveReticulumAttachment: vi.fn().mockResolvedValue({ success: false }),
      showItemInFolder: vi.fn().mockResolvedValue({ ok: true }),
      readReticulumAttachmentAsDataUrl: vi.fn().mockResolvedValue({ dataUrl: null }),
      readReticulumAttachmentBytes: vi.fn().mockResolvedValue({ dataBase64: null }),
      linkPreview: {
        fetch: vi.fn().mockResolvedValue(null),
      },
      outbox: {
        list: vi
          .fn()
          .mockImplementation((protocol: string) =>
            Promise.resolve(outboxMockRows.filter((r) => r.protocol === protocol)),
          ),
        add: vi.fn().mockImplementation((entry: OutboxEntryInput) => {
          const row = makeOutboxMockRow(entry);
          outboxMockRows.push(row);
          return Promise.resolve(row);
        }),
        updateStatus: vi
          .fn()
          .mockImplementation(
            (
              id: number,
              status: OutboxEntry['status'],
              error?: string,
              nextRetryAt?: number | null,
              attemptCount?: number,
            ) => {
              const row = outboxMockRows.find((r) => r.id === id);
              if (row) {
                row.status = status;
                if (error !== undefined) row.error = error ?? null;
                if (nextRetryAt !== undefined) row.nextRetryAt = nextRetryAt ?? null;
                if (attemptCount !== undefined) row.attemptCount = attemptCount;
                row.updatedAt = Date.now();
              }
              return Promise.resolve(undefined);
            },
          ),
        remove: vi.fn().mockImplementation((id: number) => {
          const idx = outboxMockRows.findIndex((r) => r.id === id);
          if (idx >= 0) outboxMockRows.splice(idx, 1);
          return Promise.resolve(undefined);
        }),
      },
    },
    meshtasticXmodem: {
      pickUploadFile: vi.fn().mockResolvedValue(null),
      saveDownloadFile: vi.fn().mockResolvedValue({ success: false }),
    },
    support: {
      exportBundle: vi.fn().mockResolvedValue(null),
    },
    log: {
      getPath: vi.fn().mockResolvedValue('/tmp/test.log'),
      getRecentLines: vi.fn().mockResolvedValue([]),
      clear: vi.fn().mockResolvedValue(undefined),
      export: vi.fn().mockResolvedValue(null),
      onLine: vi.fn().mockReturnValue(() => {}),
      logDeviceConnection: vi.fn().mockResolvedValue(undefined),
    },
    tak: {
      start: vi.fn().mockResolvedValue(undefined),
      stop: vi.fn().mockResolvedValue(undefined),
      getStatus: vi.fn().mockResolvedValue({ running: false, port: 8089, clientCount: 0 }),
      getConnectedClients: vi.fn().mockResolvedValue([]),
      generateDataPackage: vi.fn().mockResolvedValue(undefined),
      regenerateCertificates: vi.fn().mockResolvedValue(undefined),
      pushNodeUpdate: vi.fn().mockResolvedValue(undefined),
      onStatus: vi.fn().mockReturnValue(() => {}),
      onClientConnected: vi.fn().mockReturnValue(() => {}),
      onClientDisconnected: vi.fn().mockReturnValue(() => {}),
    },
    bleCoexistence: {
      register: vi.fn().mockResolvedValue({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      unregister: vi.fn().mockResolvedValue({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      assertCanConnect: vi.fn().mockResolvedValue({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      getState: vi.fn().mockResolvedValue({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      acquireScan: vi.fn().mockResolvedValue({
        connections: [],
        scanOwner: 'reticulum',
        nobleYieldDecisionPending: false,
      }),
      releaseScan: vi.fn().mockResolvedValue({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      pauseNobleScan: vi.fn().mockResolvedValue({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      suspendNobleForReticulumBleConnect: vi.fn().mockResolvedValue({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
    },
    reticulum: {
      start: vi.fn().mockResolvedValue({ running: true, port: 19437, pid: 1 }),
      stop: vi.fn().mockResolvedValue(undefined),
      getStatus: vi.fn().mockResolvedValue({ running: false, port: 0, pid: null }),
      syncInterfaceIssueScope: vi.fn().mockResolvedValue({ running: false, port: 0, pid: null }),
      proxyGet: vi.fn().mockResolvedValue({ status: 'ok' }),
      proxyPost: vi.fn().mockResolvedValue({ ok: true }),
      proxyPut: vi.fn().mockResolvedValue({ ok: true }),
      proxyDelete: vi.fn().mockResolvedValue({ ok: true }),
      factoryReset: vi.fn().mockResolvedValue({ ok: true }),
      readDefaultConfigFile: vi.fn().mockResolvedValue({ path: null, content: null }),
      showConfigImportDialog: vi.fn().mockResolvedValue({ path: null, content: null }),
      showIdentityImportDialog: vi
        .fn()
        .mockResolvedValue({ path: null, contentBase64: null, byteLength: null, error: null }),
      showIdentityBackupImportDialog: vi
        .fn()
        .mockResolvedValue({ path: null, contentText: null, error: null }),
      saveIdentityExportDialog: vi.fn().mockResolvedValue({ path: null, error: null }),
      saveBlocklistDialog: vi.fn().mockResolvedValue({ path: null, error: null }),
      openBlocklistDialog: vi.fn().mockResolvedValue({ hashes: null, skipped: 0, error: null }),
      showNomadContentSourceDialog: vi.fn().mockResolvedValue({ canceled: true, path: null }),
      setNomadContentSource: vi.fn().mockResolvedValue({ ok: true }),
      validateConfig: vi.fn().mockResolvedValue({ ok: true, issues: [] }),
      onEvent: vi.fn().mockReturnValue(() => {}),
      onVoiceAudio: vi.fn().mockReturnValue(() => {}),
      onStatus: vi.fn().mockReturnValue(() => {}),
      rrc: {
        listHubs: vi.fn().mockResolvedValue({ hubs: [] }),
        upsertHub: vi.fn().mockResolvedValue({ ok: true }),
        setFavorite: vi.fn().mockResolvedValue({ ok: true }),
        connect: vi.fn().mockResolvedValue({ ok: true }),
        disconnect: vi.fn().mockResolvedValue({ ok: true }),
        getStatus: vi.fn().mockResolvedValue({
          sessions: [],
          identity_hash: null,
        }),
        join: vi.fn().mockResolvedValue({ ok: true }),
        part: vi.fn().mockResolvedValue({ ok: true }),
        send: vi.fn().mockResolvedValue({ ok: true }),
        setNickname: vi.fn().mockResolvedValue({ ok: true }),
        getRooms: vi.fn().mockResolvedValue({ rooms: [] }),
      },
      rnsh: {
        connect: vi.fn().mockResolvedValue({ ok: true }),
        input: vi.fn().mockResolvedValue({ ok: true }),
        resize: vi.fn().mockResolvedValue({ ok: true }),
        disconnect: vi.fn().mockResolvedValue({ ok: true }),
        getStatus: vi.fn().mockResolvedValue({ sessions: [] }),
      },
      voice: {
        getStatus: vi.fn().mockResolvedValue({
          available: true,
          enabled: true,
          running: true,
          microphone_muted: false,
          codec: 'opus',
          active_call: null,
        }),
        call: vi.fn().mockResolvedValue({ ok: true }),
        answer: vi.fn().mockResolvedValue({ ok: true }),
        reject: vi.fn().mockResolvedValue({ ok: true }),
        hangup: vi.fn().mockResolvedValue({ ok: true }),
        mute: vi.fn().mockResolvedValue({ ok: true, microphone_muted: false }),
        sendAudio: vi.fn().mockResolvedValue({ ok: true }),
      },
      voiceMemo: {
        start: vi.fn().mockResolvedValue({ ok: true, session_id: 'test-memo-session' }),
        sendAudio: vi.fn().mockResolvedValue({ ok: true }),
        stop: vi.fn().mockResolvedValue({
          ok: true,
          ogg_base64: '',
          duration_ms: 0,
          size_bytes: 0,
          mode: 16,
        }),
        cancel: vi.fn().mockResolvedValue({ ok: true }),
      },
      rncp: {
        send: vi.fn().mockResolvedValue({ ok: true }),
        fetch: vi.fn().mockResolvedValue({ ok: true }),
        cancel: vi.fn().mockResolvedValue({ ok: true }),
        accept: vi.fn().mockResolvedValue({ ok: true }),
        reject: vi.fn().mockResolvedValue({ ok: true }),
        getStatus: vi.fn().mockResolvedValue({ transfers: [], pending_offers: [] }),
        getListener: vi
          .fn()
          .mockResolvedValue({ enabled: false, inbound_mode: 'off', allowed: [], blocked: [] }),
        setListener: vi.fn().mockResolvedValue({ ok: true }),
        announce: vi.fn().mockResolvedValue({ ok: true }),
        showOpenFileDialog: vi.fn().mockResolvedValue({ canceled: true, path: null }),
        showSaveDirectoryDialog: vi.fn().mockResolvedValue({ canceled: true, path: null }),
        revealInFolder: vi.fn().mockResolvedValue({ ok: true }),
      },
      remote: {
        pathCapability: vi.fn().mockResolvedValue({
          destination_hash: '',
          speed: 'unknown',
          via_atoms: [],
          transfer_allowed: false,
          shell_allowed: true,
        }),
        getIdentity: vi.fn().mockResolvedValue({ identity_hash: null, rncp_receive_hash: null }),
      },
      games: {
        getStatus: vi.fn().mockResolvedValue({ available: true, enabled: true, running: true }),
        listApps: vi.fn().mockResolvedValue({ apps: [] }),
        listSessions: vi.fn().mockResolvedValue({ sessions: [] }),
        getSession: vi.fn().mockResolvedValue({ session: null }),
        sendAction: vi.fn().mockResolvedValue({ ok: true }),
        resend: vi.fn().mockResolvedValue({ ok: true }),
        markRead: vi.fn().mockResolvedValue({ ok: true }),
        deleteSession: vi.fn().mockResolvedValue({ ok: true }),
      },
    },
    vault: {
      setPasscode: vi.fn().mockResolvedValue({ ok: true }),
      unlock: vi.fn().mockResolvedValue({ ok: true }),
      lock: vi.fn().mockResolvedValue({ ok: true }),
      status: vi.fn().mockResolvedValue({ configured: false, unlocked: false }),
    },
    deepLink: {
      onOpenUrl: vi.fn().mockReturnValue(() => {}),
    },
    gps: {
      exportGpx: vi.fn().mockResolvedValue({ success: false, reason: 'cancelled' }),
    },
  } satisfies ElectronAPI;
}
